blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/Vlad21022/SchemaLens/issues/new?template=bug_report.md
    about: Use this template to report a bug
  - name: Feature Request
    url: https://github.com/Vlad21022/SchemaLens/issues/new?template=feature_request.md
    about: Use this template to suggest a feature
